# What is TensorFlow?

TensorFlow is an open-source Deep Learning framework developed by Google.

# Why TensorFlow?

TensorFlow powers:

- Image Recognition
- Self Driving Cars
- Face Detection
- Voice Assistants
- Chatbots
- Recommendation Systems
- Medical Diagnosis
- AI Agents
- Object Detection
- NLP Systems
- Generative AI

# TensorFlow Learning Path
- Phase 1
- │
- ├── Tensor Basics
- ├── Operations
- ├── Variables
- ├── Data Types
- ├── Tensors
- │
- Phase 2
- │
- ├── Keras
- ├── Neural Networks
- ├── Training Models
- ├── Evaluation
- │
- Phase 3
- │
- ├── CNN
- ├── RNN
- ├── LSTM
- ├── NLP
- │
- Phase 4
- │
- ├── Transfer Learning
- ├── Custom Models
- ├── GPU Training
- ├── TensorBoard
- │
- Phase 5
- │
- ├── Advanced Deep Learning
- ├── GAN
- ├── Transformers
- ├── Production Deployment

# Phase 1: TensorFlow Fundamentals
Phase 1
│
- ├── Tensor Basics
- ├── Operations
- ├── Variables
- ├── Data Types
- ├── Tensors
- ├── Tensor Shapes
- ├── Tensor Manipulation
- ├── Broadcasting
- ├── GradientTape
- ├── TensorFlow Functions
- └── TensorFlow Math

# Module 1: What is a Tensor?

A tensor is the basic data structure in TensorFlow.

Think:

- Number      → Scalar Tensor
- List        → Vector Tensor
- Table       → Matrix Tensor
- Cube        → 3D Tensor
- Hypercube   → nD Tensor

In [3]:
import tensorflow as tf

print(tf.__version__)

2.21.0


In [2]:
print("TensorFlow is installed and working correctly.")

TensorFlow is installed and working correctly.


In [4]:
import tensorflow as tf

scalar = tf.constant(10)

vector = tf.constant([1,2,3])

matrix = tf.constant([
    [1,2],
    [3,4]
])

# Module 2: Tensor Attributes

Learn:

- Shape
- Rank
- Size
- Axis
- Dimensions

Example:

In [5]:
x = tf.constant([
    [1,2,3],
    [4,5,6]
])

print(x.shape)

(2, 3)


# Module 3: Data Types

TensorFlow supports:

- tf.int32
- tf.int64
- tf.float16
- tf.float32
- tf.float64
- tf.bool
- tf.string
- tf.complex64

In [6]:
x = tf.constant(
    [1,2,3],
    dtype=tf.float32
)

# Module 4: Tensor Creation

Learn all methods:

- tf.constant()
- tf.zeros()
- tf.ones()
- tf.fill()
- tf.eye()
- tf.range()
- tf.random.normal()
- tf.random.uniform()

In [8]:
tf.zeros((3,3))


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [9]:
tf.ones((5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:

tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Module 5: Tensor Operations

Learn:

- Addition
- Subtraction
- Multiplication
- Division
- Power
- Matrix Multiplication

In [14]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor([  1  32 729], shape=(3,), dtype=int32)


# Module 6: Broadcasting

One of the most important concepts.

Example:

In [15]:
matrix = tf.constant([
    [1,2,3],
    [4,5,6]
])

scalar = 10

print(matrix + scalar)

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


# Module 7: Reshaping

Learn:

- tf.expand_dims()
- tf.squeeze()
- tf.reshape()
- tf.transpose()

In [16]:
x = tf.range(12)

tf.reshape(x,(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

# Module 8: GradientTape

Most important concept in Deep Learning.

Example:

In [17]:
x = tf.Variable(5.0)

with tf.GradientTape() as tape:
    y = x**2

gradient = tape.gradient(y,x)

print(gradient)

tf.Tensor(10.0, shape=(), dtype=float32)


# Phase 1 Project
Linear Regression from Scratch

Build:

House Price Prediction

Learn:

- Inputs
- Outputs
- Loss
- Gradient Descent
- Optimization

---

# Phase 2: Keras & Deep Learning Foundations
Phase 2
│
- ├── Keras
- ├── Neural Networks
- ├── Training Models
- ├── Evaluation
- ├── Activation Functions
- ├── Loss Functions
- ├── Optimizers
- ├── Metrics
- ├── Callbacks
- └── Model Saving

# What is Keras?

Think:

TensorFlow = Engine

Keras = Car Controls

Keras makes deep learning easier.

### Building First Neural Network

In [18]:
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(10),
    keras.layers.Dense(1)
])

# Understanding Neural Networks
- Input Layer
-       ↓
- Hidden Layer
-       ↓
- Hidden Layer
-       ↓
- Output Layer

# Activation Functions

Learn:

- Sigmoid
- Tanh
- ReLU
- Leaky ReLU
- Softmax
- ELU
- GELU

# Loss Functions

1. Classification:

- BinaryCrossentropy
- CategoricalCrossentropy

2. Regression:

- MeanSquaredError
- MeanAbsoluteError
- HuberLoss

# Optimizers

Learn:

- SGD
- Momentum
- RMSProp
- Adam
- AdamW
- Nadam

Most popular:

Adam

# Training
- model.compile()
- model.fit()
- model.evaluate()
- model.predict()

These 4 functions form the foundation of Keras.

# Callbacks

Learn:

- EarlyStopping
- ModelCheckpoint
- ReduceLROnPlateau
- TensorBoard

# **Phase 2 Projects**
Project 1

- Digit Recognition

(MNIST)

Project 2

- Customer Churn Prediction

Project 3

- Heart Disease Prediction

Project 4

- Spam Email Classification

---

# Phase 3: Computer Vision & NLP
Phase 3

- ├── CNN
- ├── RNN
- ├── LSTM
- ├── NLP
- ├── Word Embeddings
- ├── Sequence Models
- ├── Attention
- └── Time Series

# **CNN (Convolutional Neural Networks)**

Used for:

- Images
- Videos
- Medical Scans
- Face Recognition
- Object Detection

### Architecture:

- Image
-  ↓
- Conv Layer
-  ↓
- Pooling
-  ↓
- Conv Layer
-  ↓
- Dense Layer
-  ↓
- Prediction

# Learn CNN Concepts
1. Convolution

- Feature Extraction

2. Kernel

- Small filter

    - 3x3
    - 5x5
    - 7x7
3. Pooling

Reduce image size.

Example:

- Max Pooling
- Average Pooling

# **CNN Projects**
- Cat vs Dog Classifier
- Face Mask Detection
- Plant Disease Detection
- Traffic Sign Recognition
---

# RNN

Used for sequential data.

- Sentence
- Stock Price
- Speech
- Time Series  

# LSTM

Solves memory problems in RNN.

Used in:

- Translation
- Chatbots
- Forecasting
- Speech Recognition

# NLP

Learn:

- Tokenization
- Embeddings
- Padding
- Vocabulary
- Text Classification

Libraries:

`tf.keras.preprocessing`  
TextVectorization

Projects:

- Sentiment Analysis
- News Classification
- Fake News Detection
- Chatbot

---

# **Phase 4: Professional TensorFlow**
Phase 4

- ├── Transfer Learning
- ├── Custom Models
- ├── GPU Training
- ├── TensorBoard
- ├── Mixed Precision
- ├── Distributed Training
- ├── tf.data
- └── Model Optimization

# Transfer Learning

Use pretrained models.

Examples:

- MobileNet
- ResNet
- EfficientNet
- Inception
- VGG

Workflow:

- Pretrained Model
-         ↓
- Fine Tune
-         ↓
- Custom Dataset
-         ↓
- High Accuracy

# TensorBoard

TensorFlow's dashboard.

Monitor:

- Loss
- Accuracy
- Graphs
- Weights
- Images
- Embeddings

### tf.data Pipeline

Professional data loading.

`dataset = tf.data.Dataset.from_tensor_slices(data)`

Learn:

- Batching
- Caching
- Prefetching
- Shuffling
- Parallel Loading

# GPU Training

Learn:

`tf.config.list_physical_devices('GPU')`

Understand:

CPU vs GPU
- CUDA
- cuDNN
- Memory Management- 

# Custom Models

Subclassing API:

`class MyModel(tf.keras.Model):`  
   `pass`
   

Learn:

- Custom Layers
- Custom Training Loops
- Custom Losses
- Custom Metrics

# **Phase 4 Projects**
- Medical Image Analysis
- Flower Classification
- Image Classification using ResNet
- Real-Time Camera Detection
---

# **Phase 5: Advanced Deep Learning**
Phase 5

- ├── GAN
- ├── Transformers
- ├── Diffusion Models
- ├── Reinforcement Learning
- ├── Self-Supervised Learning
- ├── Multi-Modal AI
- ├── LLM Fundamentals
- └── Production Deployment

# GAN (Generative Adversarial Networks)

Two networks:

Generator
     vs
Discriminator

Used for:

- Image Generation
- Face Generation
- Art Creation

Architecture:

- Generator
-       ↓
- Fake Image
-       ↓
- Discriminator
-       ↓
- Real or Fake

# Transformers

Revolutionized AI.

Learn:

- Attention
- Self Attention
- Multi Head Attention
- Positional Encoding
- Encoder
- Decoder

Core Idea:

**Attention Is All You Need**

# Models Based on Transformers
- GPT
- T5
- BERT
- RoBERTa
- LLaMA

# Diffusion Models

Used for image generation.

Examples:

- Stable Diffusion
- DALL·E

# Reinforcement Learning

Agent learns through rewards.

- Agent
-  ↓
- Action
-  ↓
- Environment
-  ↓
- Reward

Applications:

- Robotics
- Games
- Self-driving Cars

# Production Deployment

Learn:

- TensorFlow Serving
- TensorFlow Lite
- TensorFlow.js
- ONNX
- Docker
- Kubernetes
- FastAPI

Deployment Targets:

- Web
- Mobile
- Cloud
- Edge Devices
- IoT Devices

# Final TensorFlow Mastery Path
1. Tensor Basics
2. Tensor Operations
3. Variables
4. GradientTape
5. Keras
6. Neural Networks
7. Training
8. Evaluation
9. CNN
10. RNN
11. LSTM
12. NLP
13. Transfer Learning
14. TensorBoard
15. Custom Models
16. GPU Training
17. GAN
18. Transformers
19. Diffusion Models
20. Deployment

# Recommended Learning Order For You

Since you already know Python, NumPy, Pandas, Matplotlib, and Scikit-Learn:

- Tensor Basics
-      ↓
- Tensor Operations
-      ↓
- GradientTape
-      ↓
- Keras
-      ↓
- Neural Networks
-      ↓
- Training & Evaluation
-      ↓
- Mini Projects
-      ↓
- CNN
-      ↓
- Transfer Learning
-      ↓
- NLP
-      ↓
- Transformers
-      ↓
- Deployment