# TensorFlow Basic Exercises (Level 1)

These exercises are designed to build a solid foundation in TensorFlow before moving to Keras, Neural Networks, CNNs, and advanced Deep Learning.

Concepts Covered
- ✅ Tensor Creation
- ✅ Data Types
- ✅ Shape & Rank
- ✅ Tensor Operations
- ✅ Reshaping
- ✅ Variables
- ✅ Tensor Manipulation
- ✅ Matrix Multiplication
- ✅ Basic TensorFlow Functions

# Exercise 1: Tensor Creation and Properties
Problem 1

Create a scalar tensor with value 25.

Solution

In [1]:
import tensorflow as tf

scalar = tf.constant(25)

print(scalar)
print("Shape:", scalar.shape)
print("Rank:", tf.rank(scalar))

tf.Tensor(25, shape=(), dtype=int32)
Shape: ()
Rank: tf.Tensor(0, shape=(), dtype=int32)


# Problem 2

Create a vector containing:

[10, 20, 30, 40, 50]

Print:

- Tensor
- Shape
- Rank  

Solution

In [2]:
import tensorflow as tf

vector = tf.constant([10, 20, 30, 40, 50])

print(vector)
print("Shape:", vector.shape)
print("Rank:", tf.rank(vector))

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
Shape: (5,)
Rank: tf.Tensor(1, shape=(), dtype=int32)


# Problem 3

Create a 3×3 matrix.

1 2 3  
4 5 6  
7 8 9   

Solution

In [3]:
import tensorflow as tf

matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
print("Shape:", matrix.shape)
print("Rank:", tf.rank(matrix))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Shape: (3, 3)
Rank: tf.Tensor(2, shape=(), dtype=int32)


# Problem 4

Create a tensor of all zeros with shape:

(4,4)  

Solution

In [4]:
import tensorflow as tf

zeros = tf.zeros((4,4))

print(zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


# Problem 5

Create a tensor of all ones with shape:

(3,5)  

Solution

In [5]:
import tensorflow as tf

ones = tf.ones((3,5))

print(ones)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)


--- 

# Exercise 2: Data Types and Conversion
### Problem 1

Create a tensor with dtype:

tf.float32  

Solution

In [6]:
import tensorflow as tf

x = tf.constant(
    [1,2,3],
    dtype=tf.float32
)

print(x)
print(x.dtype)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
<dtype: 'float32'>


# Problem 2

Create a boolean tensor.

Solution

In [7]:
import tensorflow as tf

x = tf.constant(
    [True, False, True]
)

print(x)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


# Problem 3

Create a string tensor.

Solution

In [8]:
import tensorflow as tf

x = tf.constant([
    "TensorFlow",
    "Deep Learning"
])

print(x)

tf.Tensor([b'TensorFlow' b'Deep Learning'], shape=(2,), dtype=string)


# Problem 4

Convert an integer tensor to float32.

Solution

In [9]:
import tensorflow as tf

x = tf.constant(
    [1,2,3],
    dtype=tf.int32
)

y = tf.cast(
    x,
    tf.float32
)

print(y)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


# Problem 5

Print dtype of:

tf.constant([1.5,2.5,3.5])

In [10]:
import tensorflow as tf

x = tf.constant([1.5,2.5,3.5])

print(x.dtype)

<dtype: 'float32'>


--- 

# Exercise 3: Tensor Operations
### Problem 1

Add two tensors:

[1,2,3]

[4,5,6]  

Solution

In [11]:
import tensorflow as tf

a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

print(a+b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


# Problem 2

Subtract:

[10,20,30]

[5,10,15]  

Solution

In [12]:
import tensorflow as tf

a = tf.constant([10,20,30])
b = tf.constant([5,10,15])

print(a-b)

tf.Tensor([ 5 10 15], shape=(3,), dtype=int32)


# Problem 3

Multiply:

[2,4,6]

[3,5,7]  

Solution

In [13]:
import tensorflow as tf

a = tf.constant([2,4,6])
b = tf.constant([3,5,7])

print(a*b)

tf.Tensor([ 6 20 42], shape=(3,), dtype=int32)


# Problem 4

Divide:

[10,20,30]

[2,4,5]  

Solution

In [14]:
import tensorflow as tf

a = tf.constant([10,20,30])
b = tf.constant([2,4,5])

print(a/b)

tf.Tensor([5. 5. 6.], shape=(3,), dtype=float64)


# Calculate square of:

[2,3,4]
Solution

In [15]:
import tensorflow as tf

x = tf.constant([2,3,4])

print(tf.square(x))

tf.Tensor([ 4  9 16], shape=(3,), dtype=int32)


---

# Exercise 4: Shape and Reshaping
### Problem 1

Create:

[1,2,3,4,5,6]

Convert into:

2 x 3

matrix.

Solution

In [16]:
import tensorflow as tf

x = tf.constant([1,2,3,4,5,6])

y = tf.reshape(
    x,
    (2,3)
)

print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


# Problem 2

Create:

1 2  
3 4  
5 6

Print shape.

Solution

In [17]:
import tensorflow as tf

x = tf.constant([
    [1,2],
    [3,4],
    [5,6]
])

print(x.shape)

(3, 2)


# Problem 3

Create:

3 x 4

random tensor.

Solution

In [18]:
import tensorflow as tf

x = tf.random.normal(
    (3,4)
)

print(x)

tf.Tensor(
[[ 2.1286035e-01  1.2224387e+00 -5.0463206e-01  1.5339708e+00]
 [-2.2873387e+00 -1.8629839e+00 -4.5636777e-02  3.6842452e-05]
 [-8.5065317e-01  1.1198262e+00 -4.4524220e-01 -9.3769050e-01]], shape=(3, 4), dtype=float32)


# Problem 4

Expand dimension of:

[1,2,3]  

Solution

In [19]:
import tensorflow as tf

x = tf.constant([1,2,3])

y = tf.expand_dims(
    x,
    axis=0
)

print(y)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


# Problem 5

Remove extra dimension.

Solution

In [20]:
import tensorflow as tf

x = tf.constant([
    [[1,2,3]]
])

y = tf.squeeze(x)

print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


# Exercise 5: Variables and Matrix Multiplication
### Problem 1

Create a variable:

weight = 10  

Solution

In [21]:
import tensorflow as tf

weight = tf.Variable(10)

print(weight)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


# Problem 2

Update variable value to:

50  

Solution

In [22]:
import tensorflow as tf

weight = tf.Variable(10)

weight.assign(50)

print(weight)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>


# Problem 3

Matrix multiplication.

Matrix A:

1 2  
3 4

Matrix B:

5 6  
7 8  

Solution

In [23]:
import tensorflow as tf

a = tf.constant([
    [1,2],
    [3,4]
])

b = tf.constant([
    [5,6],
    [7,8]
])

print(
    tf.matmul(a,b)
)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Problem 4

Create identity matrix of size 5.

Solution

In [24]:
import tensorflow as tf

identity = tf.eye(5)

print(identity)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


# Problem 5

Generate random tensor of shape:

(2,3)

using uniform distribution.

Solution

In [25]:
import tensorflow as tf

x = tf.random.uniform(
    (2,3)
)

print(x)

tf.Tensor(
[[0.23515666 0.5778595  0.81366134]
 [0.8005738  0.08548653 0.39837432]], shape=(2, 3), dtype=float32)
