# TensorFlow Intermediate Exercises (Level 2)

Now we move beyond basic tensor creation and operations.

These exercises are designed to strengthen your understanding of:
- ✅ Tensor Indexing & Slicing
- ✅ Broadcasting
- ✅ Tensor Manipulation
- ✅ Mathematical Operations
- ✅ GradientTape
- ✅ tf.data Dataset API
- ✅ Variables
- ✅ Matrix Operations
- ✅ TensorFlow Workflow

# Exercise 1: Tensor Indexing, Slicing, and Manipulation
Problem Statement

Create the following tensor:

[  
 [10,20,30,40],  
 [50,60,70,80],  
 [90,100,110,120]  
]

Perform the following tasks:

- Print the tensor shape.
- Print the first row.
- Print the second column.  
Extract:
[  
 [60,70],  
 [100,110]  
]  

Reshape the tensor into shape (4,3).

In [1]:
import tensorflow as tf

x = tf.constant([
    [10,20,30,40],
    [50,60,70,80],
    [90,100,110,120]
])

print("Shape:")
print(x.shape)

print("\nFirst Row:")
print(x[0])

print("\nSecond Column:")
print(x[:,1])

print("\nSub Tensor:")
print(x[1:,1:3])

print("\nReshaped:")
print(tf.reshape(x,(4,3)))

Shape:
(3, 4)

First Row:
tf.Tensor([10 20 30 40], shape=(4,), dtype=int32)

Second Column:
tf.Tensor([ 20  60 100], shape=(3,), dtype=int32)

Sub Tensor:
tf.Tensor(
[[ 60  70]
 [100 110]], shape=(2, 2), dtype=int32)

Reshaped:
tf.Tensor(
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]], shape=(4, 3), dtype=int32)


# Exercise 2: Broadcasting and Tensor Math
Problem Statement

Create:

A =  
[  
 [1,2,3],  
 [4,5,6]  
]

Perform:

- Add scalar 10.
- Multiply by scalar 2.
- Calculate square.
- Calculate cube.
- Calculate mean of all elements.  

Solution

In [2]:
import tensorflow as tf

A = tf.constant([
    [1,2,3],
    [4,5,6]
])

print("Add 10")
print(A + 10)

print("\nMultiply by 2")
print(A * 2)

print("\nSquare")
print(tf.square(A))

print("\nCube")
print(tf.pow(A,3))

print("\nMean")
print(tf.reduce_mean(A))

Add 10
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)

Multiply by 2
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)

Square
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)

Cube
tf.Tensor(
[[  1   8  27]
 [ 64 125 216]], shape=(2, 3), dtype=int32)

Mean
tf.Tensor(3, shape=(), dtype=int32)


# Exercise 3: Matrix Operations Challenge
Problem Statement

Create:

A =
[  
 [1,2],  
 [3,4]  
]

B =
[  
 [5,6],  
 [7,8]  
]

Perform:

- Matrix multiplication.
- Matrix addition.
- Matrix subtraction.
- Matrix transpose of A.
- Find determinant of A.  

Solution

In [3]:
import tensorflow as tf

A = tf.constant([
    [1.,2.],
    [3.,4.]
])

B = tf.constant([
    [5.,6.],
    [7.,8.]
])

print("Matrix Multiplication")
print(tf.matmul(A,B))

print("\nAddition")
print(A+B)

print("\nSubtraction")
print(A-B)

print("\nTranspose")
print(tf.transpose(A))

print("\nDeterminant")
print(tf.linalg.det(A))

Matrix Multiplication
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)

Addition
tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)

Subtraction
tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)

Transpose
tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)

Determinant
tf.Tensor(-2.0, shape=(), dtype=float32)


# Exercise 4: Variables and GradientTape
Problem Statement

1. Create a variable:

x = 4.0

Using GradientTape:

2. Calculate:
y = x² + 3x + 5
3. Compute gradient.
4. Print gradient.
5. Update x by subtracting:  
0.1 × gradient
6. Print updated x.  

Solution

In [4]:
import tensorflow as tf

x = tf.Variable(4.0)

with tf.GradientTape() as tape:

    y = x**2 + 3*x + 5

gradient = tape.gradient(y,x)

print("Gradient:")
print(gradient)

x.assign_sub(
    0.1 * gradient
)

print("\nUpdated x:")
print(x)

Gradient:
tf.Tensor(11.0, shape=(), dtype=float32)

Updated x:
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.9000000953674316>


# Exercise 5: Complete TensorFlow Workflow
Problem Statement

Create a TensorFlow pipeline that:

- Creates numbers from 1–20.
- Converts them into a Dataset.
- Squares every number.
- Filters only even squares.
- Batches into groups of 4.
- Print the final batches.

In [5]:
import tensorflow as tf

numbers = tf.range(1,21)

dataset = tf.data.Dataset.from_tensor_slices(
    numbers
)

dataset = dataset.map(
    lambda x: x**2
)

dataset = dataset.filter(
    lambda x: x % 2 == 0
)

dataset = dataset.batch(4)

for batch in dataset:
    print(batch)

tf.Tensor([ 4 16 36 64], shape=(4,), dtype=int32)
tf.Tensor([100 144 196 256], shape=(4,), dtype=int32)
tf.Tensor([324 400], shape=(2,), dtype=int32)


# Intermediate Mastery Checklist

After solving these 5 exercises on your own, you should be comfortable with:

- Tensor indexing
- Tensor slicing
- Broadcasting
- Reshaping
- Matrix multiplication
- Matrix transpose
- TensorFlow math functions
- Variables
- Automatic differentiation
- Gradient computation
- Dataset pipelines
- Data batching
- TensorFlow workflow basics